version: '3.8'

services:
  backend:
    build: ./backend
    container_name: customer-lifecycle-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/customer_lifecycle.db
      - PYTHONPATH=/app
    volumes:
      - ./datasets:/app/datasets:ro
      - backend_data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: customer-lifecycle-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge