version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer-lifecycle-backend-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/customer_lifecycle.db
      - PYTHONPATH=/app
      - RELOAD=true
    volumes:
      - ./backend:/app
      - ./datasets:/app/datasets:ro
      - backend_data:/app/data
    networks:
      - app-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      target: build
    container_name: customer-lifecycle-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge